version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgress"
      POSTGRES_DB: "propostadb"
    ports:
      - "5433:5432"
    volumes:
      - proposta-db:/var/lib/postgresql/data

volumes:
  proposta-db:
