version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: book_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3311:3306"
    volumes:
      - book-db:/var/lib/mysql

volumes:
  book-db:
